version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: tutoring-backend
    restart: always
    volumes:
      - ./server:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      POSTGRES_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./client
    container_name: tutoring-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: