"""Added payment_ref and zoom_link

Revision ID: 029bc3fe59c2
Revises: 
Create Date: 2025-03-15 12:33:43.719851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029bc3fe59c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['payment_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('payment_ref')

    # ### end Alembic commands ###
