"""Add tables for assessments and plans

Revision ID: 35510a341ad1
Revises: f1ad509597aa
Create Date: 2025-04-05 15:46:16.122234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35510a341ad1'
down_revision = 'f1ad509597aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confidence_descriptor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('confidence_descriptor_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic_question', ['question_id'], ['id'])
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('topic_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('topic_assessment_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic_question', ['question_id'], ['id'])
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('topic_assessment_topic_id_fkey', 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('question_id')

    with op.batch_alter_table('confidence_descriptor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('confidence_descriptor_topic_id_fkey', 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
