"""zoom meeting id

Revision ID: 3f6690cc92ff
Revises: b3163d2a09b3
Create Date: 2025-03-15 14:30:08.572809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6690cc92ff'
down_revision = 'b3163d2a09b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zoom_meeting_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('zoom_meeting_id')

    # ### end Alembic commands ###
