"""Add tables for assessment

Revision ID: 3f6dac75e4fe
Revises: 35510a341ad1
Create Date: 2025-04-06 12:03:26.939112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6dac75e4fe'
down_revision = '35510a341ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('maths_paper', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('exam_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('exam_date')
        batch_op.drop_column('maths_paper')
        batch_op.drop_column('target_grade')

    # ### end Alembic commands ###
