"""Add field for completed on weekly plan, and added relationship between booking and plan

Revision ID: a713c79373bb
Revises: 3f6dac75e4fe
Create Date: 2025-04-07 21:17:17.473679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a713c79373bb'
down_revision = '3f6dac75e4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_topic', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('weekly_plan_subtopic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'weekly_plan_subtopic', ['weekly_plan_subtopic_id'], ['id'])
        batch_op.drop_column('topic')

    with op.batch_alter_table('weekly_plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_plan_entry', schema=None) as batch_op:
        batch_op.drop_column('completed')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('weekly_plan_subtopic_id')
        batch_op.drop_column('custom_topic')

    # ### end Alembic commands ###
