"""Added zoom_link to bookings

Revision ID: b3163d2a09b3
Revises: 029bc3fe59c2
Create Date: 2025-03-15 14:14:48.655453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3163d2a09b3'
down_revision = '029bc3fe59c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zoom_link', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('zoom_link')

    # ### end Alembic commands ###
