"""Add plan_id and week_number to Booking

Revision ID: bceba51e5a1b
Revises: a713c79373bb
Create Date: 2025-04-08 00:41:49.838440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bceba51e5a1b'
down_revision = 'a713c79373bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'weekly_plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('week_number')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
