"""Renamed notes_path to notes_filename

Revision ID: ce43fc076742
Revises: 65f276ff4665
Create Date: 2025-03-16 16:36:47.455455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce43fc076742'
down_revision = '65f276ff4665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('notes_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('notes_filename')

    # ### end Alembic commands ###
